const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1366,height:950}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 let starts=0, complete=false;
 const records=Array.from({length:25},(_,i)=>({adArchiveId:'search-'+i,pageName:'Anunciante '+i,adText:'Un mensaje que conecta con nuestra audiencia.'}));
 await page.route('**/api/runs',route=>{starts++;return route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({id:'mock-run',status:'RUNNING'})})});
 await page.route('**/api/runs/mock-run',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({id:'mock-run',status:complete?'SUCCEEDED':'RUNNING',...(complete?{items:records}:{})})}));
 await page.goto('http://127.0.0.1:5094/login');await page.locator('#username').fill('leadsicon');await page.locator('#password').fill('browser-test-password');await page.getByRole('button',{name:'Ingresar',exact:true}).click();await page.waitForURL('http://127.0.0.1:5094/');
 await page.goto('http://127.0.0.1:5094/ads');await page.locator('#keywords').fill('Cheap Insurance');await page.getByRole('button',{name:'Buscar anuncios →',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Explorando'));
 if(!(await page.locator('#search-panel').isHidden()))throw Error('form should hide');
 if(!(await page.locator('#scraper-progress').isVisible()))throw Error('progress should animate');
 await page.screenshot({animations:'disabled',path:'/tmp/leadsicon-search-progress.png'});
 await page.getByRole('link',{name:'✦   Crear contenido'}).first().click();await page.waitForURL('http://127.0.0.1:5094/');
 complete=true;await page.getByRole('link',{name:'→   Explorar anuncios'}).first().click();
 await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Búsqueda completada'));
 if(starts!==1)throw Error('duplicate paid run on resume');
 if(await page.locator('#results .ad-card').count()!==12)throw Error('pagination page 1');
 await page.locator('#next-page').click();if(await page.locator('#results .ad-card').count()!==12)throw Error('pagination page 2');
 await page.locator('#next-page').click();if(await page.locator('#results .ad-card').count()!==1)throw Error('pagination page 3');
 await page.reload();await page.locator('#results .ad-card').waitFor();if(await page.locator('#results .ad-card').count()!==1)throw Error('page not persisted');
 if(starts!==1)throw Error('duplicate run on reload');
 await page.locator('#previous-page').click();await page.locator('#previous-page').click();
 await page.getByRole('button',{name:'♡ Guardar',exact:true}).first().click();await page.getByRole('button',{name:'♥ Guardado',exact:true}).waitFor();
 await page.getByRole('link',{name:'Ver ficha →',exact:true}).first().click();
 await page.locator('#transcript-editor summary').click();
 await page.getByRole('button',{name:'＋ Añadir voz'}).click();await page.locator('#speech-rows [data-field=text]').fill('Hello, this is the spoken audio.');await page.locator('#speech-rows [data-field=role]').selectOption('voiceover');
 await page.getByRole('button',{name:'＋ Añadir escena'}).click();await page.locator('#scene-rows [data-field=description]').fill('Una persona muestra el interior del auto.');
 await page.getByRole('button',{name:'Guardar transcripciones',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#transcript-status').textContent.includes('Versión 1 guardada'));
 await page.getByRole('button',{name:'◎ Voz',exact:true}).click();if(!(await page.locator('#transcript-timeline').textContent()).includes('VoiceOver'))throw Error('missing speaker roles');
 await page.getByRole('button',{name:'▣ Escenas',exact:true}).click();if(!(await page.locator('#transcript-timeline').textContent()).includes('interior del auto'))throw Error('missing scenes');
 // A polling refresh must preserve unsaved corrections.
 await page.locator('#speech-rows [data-field=text]').fill('Unsaved correction');await page.locator('#refresh-detail').click();await page.waitForTimeout(500);if(await page.locator('#speech-rows [data-field=text]').inputValue()!=='Unsaved correction')throw Error('poll overwrote editing');
 await page.reload();await page.waitForFunction(()=>document.querySelector('#transcript-version').options[0].textContent.includes('Versión 1'));
 await page.goto('http://127.0.0.1:5094/ads');await page.locator('#results .ad-card').first().waitFor();if(starts!==1)throw Error('duplicate after detail');
 await page.screenshot({animations:'disabled',path:'/tmp/leadsicon-search-results.png'});
 await page.locator('[data-theme-toggle]').click();await page.screenshot({animations:'disabled',path:'/tmp/leadsicon-search-dark.png'});
 await page.setViewportSize({width:390,height:844});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error('mobile overflow');
 await page.screenshot({animations:'disabled',path:'/tmp/leadsicon-search-mobile.png'});
 await page.locator('#edit-search').click();if(!(await page.locator('#search-panel').isVisible()))throw Error('edit form');await page.locator('#view-results').click();if(!(await page.locator('#results-panel').isVisible()))throw Error('return results');
 await page.getByRole('button',{name:'Salir →',exact:true}).click();await page.waitForURL('http://127.0.0.1:5094/login');if(await page.evaluate(()=>sessionStorage.getItem('leadsicon-ads-search-v2'))!==null)throw Error('logout cache not cleared');
 if(errors.length)throw Error(errors.join('; '));
 console.log('Browser OK: active search survives Studio navigation, no duplicate runs, completed results and page persist, 12-card pagination, favorite, voice/scene timeline, edits survive refresh, glass light/dark/mobile, cache cleared on logout.');await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
